### PR TITLE
Django 4 support

### LINKED ISSUE #3: Package uses deprecated JSONField model fields
When installing django-pgstats, django's checks provide the following notes:

```
pgstats.IndexStats.stats: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
    HINT: Use django.db.models.JSONField instead.
pgstats.TableStats.stats: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
    HINT: Use django.db.models.JSONField instead.
```

Recommend updating file https://github.com/Opus10/django-pgstats/blob/master/pgstats/models.py to import and use `django.db.models.JSONField`

### PR DESCRIPTION
**Pull request by JackAtOmenApps**
Simply modifies imports in models.py and the migration file to use a try/except, and updates the existing migration to use the results of this modified import.

This should have zero effect on existing installs using django<4, but will enable upgrading to use the package with django>=4.

Fixes #3 and only makes a tiny change to resolve the issue (in comparison to #4 which might be trying to accomplish too much for a PR focused on updating to Django4+)

### CODE REVIEW

**Comment by JackAtOmenApps** [comment]
It looks like there is an issue with CircleCI preventing checks. Any recommendations?

**Comment by jacklinke** [comment]
@wesleykendall @tomage - any thoughts / recommendations on this PR which resolves the Django 4 issues?

**Comment by jacklinke** [comment]
Bumping. Any thoughts or questions on this PR?

**Comment by wesleykendall** [comment]
@OmenApps @jacklinke I will update this PR so that checks pass and get it deployed.

**Comment by wesleykendall** [comment]
FYI I updated the implementation so that there's a fixed path for JSONField similar to how it's accomplished in [django-pghistory](https://github.com/Opus10/django-pghistory/blob/master/pghistory/utils.py#L10). With this implementation, the bug won't be re-introduced if new migrations are made.

I also went ahead and included a second commit in this PR so that this library is up to date with the template that I use for all Django libraries.

Apologies for the delay. django-pgtrigger and django-pghistory (plus other pg* projects) have been taking up most of my time. If you need other fixes for this library, feel free to tag me again to get my attention, otherwise it might get buried in my inbox

I will close the related issue once this fix is on pypi

**Pull request merged**
